Support MySQL Milestone 1
paashzj/paas_dashboard_flutter pull request #54
Opened 2022-01-21 09:04 UTC by HaitaoDeng

2022-01-21 09:13 UTC, HaitaoDeng commented
![image](https://user-images.githubusercontent.com/31698031/150499795-59587559-c09e-426a-8051-1a6aa6c8b38f.png)
![image](https://user-images.githubusercontent.com/31698031/150499816-d050c507-f586-4ea2-9b94-d187e667e22e.png)
![image](https://user-images.githubusercontent.com/31698031/150499846-995b6dd1-3066-46df-ab0a-b267032a8b7c.png)
three Windows

2022-01-21 09:18 UTC, goflutterjava requested changes

2022-01-21 09:18 UTC, goflutterjava commented on lib/l10n/intl_en.arb
>  }
arb file is sort by lexicographical order

2022-01-21 09:18 UTC, goflutterjava commented on lib/l10n/intl_zh.arb
> +  "database": "数据库",
arb file is sort by lexicographical order

2022-01-21 09:18 UTC, goflutterjava commented on lib/module/mysql/const.dart
> +  static const String defaultPassword = "123456";
no need to commit

2022-01-21 09:24 UTC, goflutterjava commented on lib/ui/mysql/mysql_page.dart
> +                          Navigator.of(context).pushNamed(PageRouteConst.MysqlInstance, arguments: itemRow.deepCopy());
why change this?

2022-01-21 09:24 UTC, goflutterjava commented on lib/ui/mysql/mysql_page.dart
> +/// MySQL实例列表页面
use english annotation

2022-01-21 09:24 UTC, goflutterjava commented on lib/ui/mysql/widget/mysql_database.dart
> +/// mysql 数据库列表
use english annotation

2022-01-21 09:25 UTC, goflutterjava commented on lib/ui/mysql/widget/mysql_tables.dart
> +    // return body;
nits.

2022-01-21 09:25 UTC, goflutterjava commented on lib/vm/mysql/mysql_database_view_model.dart
> +import '../base_load_list_page_view_model.dart';
use absolute import path

2022-01-21 09:25 UTC, goflutterjava commented on lib/vm/mysql/mysql_user_view_model.dart
> +import '../base_load_list_page_view_model.dart';
use absolute import path.

2022-01-21 09:26 UTC, goflutterjava commented on lib/vm/mysql/mysql_table_data_view_model.dart
> +import '../base_load_list_page_view_model.dart';
use absolute import

2022-01-21 09:26 UTC, goflutterjava commented on lib/vm/mysql/mysql_table_data_view_model.dart
> +class MysqlTableDetailViewModel extends BaseLoadListPageViewModel<Object> {
why we use `Object` here?

2022-01-21 09:26 UTC, goflutterjava commented on lib/ui/mysql/widget/mysql_tables.dart
> +/// mysql 数据库表list界面
use english annotation

2022-01-21 09:27 UTC, goflutterjava commented on lib/ui/mysql/widget/mysql_table_detail.dart
> +/// MySQL 表数据展示
please use english annotation

2022-01-21 09:30 UTC, zxJin-x requested changes

2022-01-21 09:30 UTC, zxJin-x commented on lib/l10n/intl_zh.arb
> +  "tables": "数据库表表",
数据库表表？

2022-01-21 09:58 UTC, zxJin-x commented on lib/ui/mysql/widget/mysql_database.dart
> +          'Mysql Database',
![image](https://user-images.githubusercontent.com/40939066/150506698-c1918284-f8f5-4e13-9b47-6924435276db.png)
是不是有点重复了

2022-01-21 09:58 UTC, zxJin-x requested changes

2022-01-21 09:58 UTC, zxJin-x commented on lib/ui/mysql/widget/mysql_tables.dart
> +          'Mysql tables',
做国际化

2022-01-21 09:59 UTC, zxJin-x commented on lib/ui/mysql/widget/mysql_tables.dart
> +        SearchableTitle("database list", "search by database name", searchTextController),
database list做国际化

2022-01-21 09:59 UTC, zxJin-x commented on lib/ui/mysql/widget/mysql_user.dart
> +          'Mysql User Name',
国际化

2022-01-21 10:20 UTC, jiaob commented on lib/api/mysql/mysql_databases_api.dart
> +    var rr = await conn.query('show databases');
The variable name is incorrect.

2022-01-21 14:05 UTC, goflutterjava commented
@HaitaoDeng Please ping me if you have addressed all problems
cc @jiaob @zxJin-x @fu-turer

2022-01-22 01:45 UTC, goflutterjava requested changes

2022-01-22 01:45 UTC, goflutterjava commented on lib/main.dart
> +        if (settings.name == PageRouteConst.MysqlInstance) {
suggest put mysql under mongo. lexicographical order

2022-01-22 01:45 UTC, goflutterjava commented on lib/route/route_gen.dart
> +  static Route mysqlInstance(MysqlInstanceViewModel viewModel) {
same, under mongo, lexicographical

2022-01-22 01:45 UTC, goflutterjava commented on lib/ui/mysql/mysql_instance.dart
> +/// MySQL单个实例，数据库列表页面
english annotation

2022-01-22 01:45 UTC, goflutterjava commented on lib/ui/mysql/mysql_instance.dart
> +            Tab(text: "Details"),
i10n

2022-01-22 01:45 UTC, goflutterjava commented on lib/ui/mysql/mysql_instance.dart
> +              text: "databases",
i10n

2022-01-22 01:45 UTC, goflutterjava commented on lib/vm/mysql/mysql_instance_view_model.dart
> +import '../base_load_list_page_view_model.dart';
absoulte import

2022-01-22 01:45 UTC, goflutterjava commented on lib/vm/mysql/mysql_table_view_model.dart
> +import '../base_load_list_page_view_model.dart';
absoulte import

2022-01-22 02:34 UTC, goflutterjava commented on lib/main.dart
> +
unneeded space line

2022-01-22 03:24 UTC, goflutterjava commented
@HaitaoDeng are this changes need for format ?
![image](https://user-images.githubusercontent.com/95280282/150623044-951e0ab2-4ab0-4d41-9912-5d7c3538f32f.png)

2022-01-22 06:14 UTC, HaitaoDeng commented
> @HaitaoDeng are this changes need for format ? ![image](https://user-images.githubusercontent.com/95280282/150623044-951e0ab2-4ab0-4d41-9912-5d7c3538f32f.png)

misoperation will not affect?

2022-01-22 07:38 UTC, goflutterjava approved these changes

2022-01-22 07:38 UTC, merged